"""Module: models/communication.py

Pydantic models for communication drafting and validation in VQMS.

These models define the shape of response emails drafted by the
Communication Drafting Agent and the validation reports produced
by the Quality & Governance Gate.

Corresponds to Steps 8-9 in the VQMS architecture document.
"""

from __future__ import annotations

from datetime import datetime

from pydantic import BaseModel, Field


class DraftEmailPackage(BaseModel):
    """A response email draft generated by the Communication Drafting Agent.

    Contains the full email content ready to be sent to the vendor,
    including the ticket number reference and SLA commitment.
    Must pass the Quality Gate before being sent.
    """

    ticket_id: str = Field(
        description="ServiceNow ticket number to reference in the email"
    )
    recipient_email: str = Field(
        description="Vendor email address to send the response to"
    )
    subject: str = Field(
        description="Email subject line (usually 'Re: <original subject>')"
    )
    body_html: str = Field(
        description="HTML formatted email body for rich email clients"
    )
    body_plain: str = Field(
        description="Plain text fallback for email clients that don't render HTML"
    )
    sla_promise: str = Field(
        description="SLA commitment text (e.g., 'within 24 hours')"
    )
    includes_ticket_number: bool = Field(
        description="True if the draft body contains the ticket number. "
        "Quality Gate will reject drafts without ticket numbers.",
    )
    is_template_compliant: bool = Field(
        description="True if the draft follows the company email template. "
        "Quality Gate checks this against the approved templates.",
    )
    generated_at: datetime = Field(
        description="When this draft was generated by the Drafting Agent"
    )


class ValidationReport(BaseModel):
    """Quality Gate validation results for a drafted email.

    The Quality & Governance Gate runs four checks on every draft
    before it can be sent to a vendor. All four must pass for the
    overall validation to succeed.
    """

    # Check 1: Ticket number — draft must reference the correct ticket
    ticket_number_valid: bool = Field(
        description="True if the ticket number in the draft is correct"
    )
    ticket_number_present: bool = Field(
        description="True if a ticket number appears in the draft body"
    )

    # Check 2: SLA wording — draft must include appropriate SLA commitment
    sla_wording_valid: bool = Field(
        description="True if the SLA wording matches the vendor's tier"
    )
    sla_wording_description: str | None = Field(
        default=None,
        description="Description of what SLA wording was found (for audit)",
    )

    # Check 3: PII detection — draft must not contain personal data
    pii_detected: bool = Field(
        description="True if PII was found in the draft (must be False to pass)"
    )
    pii_details: list[str] = Field(
        default_factory=list,
        description="List of PII types detected (e.g., 'SSN', 'credit_card')",
    )

    # Check 4: Template compliance — draft must follow approved format
    template_compliant: bool = Field(
        description="True if the draft follows the company email template"
    )
    template_issues: list[str] = Field(
        default_factory=list,
        description="List of template compliance issues found",
    )

    # Overall result
    overall_valid: bool = Field(
        description="True only if ALL four checks pass. "
        "Failed drafts are sent to vqms-human-review queue.",
    )
    validated_at: datetime = Field(
        description="When this validation was performed"
    )
